/**
 * Single source of truth for demo category metadata.
 * Media, seed quotas, sizes, pricing, related products, and try-on consult this module.
 */

export type SizeProfile = "adult" | "kids" | "waist" | "one";
export type PriceBand =
  | "tee"
  | "shirt"
  | "bottom"
  | "outer"
  | "dress"
  | "ethnic"
  | "saree"
  | "bridal"
  | "kids";

export type CategoryMeta = {
  slug: string;
  segment: string;
  gender: "men" | "women" | "kids" | "unisex";
  productType: string;
  subType: string;
  tryOnSupported: boolean;
  compatibleRelated: string[];
  sizeProfile: SizeProfile;
  priceBand: PriceBand;
  nameTokens: string[];
  descTokens: string[];
  skuType: string;
  brandSlug: string;
  quota: number;
};

function m(
  partial: Omit<CategoryMeta, "nameTokens" | "descTokens"> & {
    nameTokens?: string[];
    descTokens?: string[];
  },
): CategoryMeta {
  const nameTokens = partial.nameTokens ?? [partial.subType.replace(/-/g, " ")];
  const descTokens = partial.descTokens ?? nameTokens;
  return { ...partial, nameTokens, descTokens };
}

/** Per-leaf quotas sum to 702 (apparel only; overlapping kurta lines removed). */
export const CATEGORY_META: Record<string, CategoryMeta> = {
  // â€”â€” Men (~222) â€”â€”
  "men-t-shirts": m({
    slug: "men-t-shirts",
    segment: "men",
    gender: "men",
    productType: "tops",
    subType: "t-shirt",
    tryOnSupported: true,
    compatibleRelated: ["men-oversized-tees", "men-graphic-tees", "men-polos"],
    sizeProfile: "adult",
    priceBand: "tee",
    nameTokens: ["t-shirt", "tee"],
    skuType: "MTS",
    brandSlug: "t360-essentials",
    quota: 35,
  }),
  "men-oversized-tees": m({
    slug: "men-oversized-tees",
    segment: "men",
    gender: "men",
    productType: "tops",
    subType: "oversized-tee",
    tryOnSupported: true,
    compatibleRelated: ["men-t-shirts", "men-graphic-tees", "men-hoodies"],
    sizeProfile: "adult",
    priceBand: "tee",
    nameTokens: ["t-shirt", "tee", "oversized"],
    skuType: "MOT",
    brandSlug: "t360-studio",
    quota: 12,
  }),
  "men-graphic-tees": m({
    slug: "men-graphic-tees",
    segment: "men",
    gender: "men",
    productType: "tops",
    subType: "graphic-tee",
    tryOnSupported: true,
    compatibleRelated: ["men-t-shirts", "men-oversized-tees"],
    sizeProfile: "adult",
    priceBand: "tee",
    nameTokens: ["t-shirt", "tee", "graphic"],
    skuType: "MGT",
    brandSlug: "t360-studio",
    quota: 12,
  }),
  "men-polos": m({
    slug: "men-polos",
    segment: "men",
    gender: "men",
    productType: "tops",
    subType: "polo",
    tryOnSupported: true,
    compatibleRelated: ["men-t-shirts", "men-casual-shirts"],
    sizeProfile: "adult",
    priceBand: "tee",
    nameTokens: ["polo"],
    skuType: "MPO",
    brandSlug: "t360-essentials",
    quota: 10,
  }),
  "men-casual-shirts": m({
    slug: "men-casual-shirts",
    segment: "men",
    gender: "men",
    productType: "tops",
    subType: "casual-shirt",
    tryOnSupported: true,
    compatibleRelated: ["men-formal-shirts", "men-linen-shirts", "men-polos"],
    sizeProfile: "adult",
    priceBand: "shirt",
    nameTokens: ["shirt"],
    skuType: "MCS",
    brandSlug: "t360-studio",
    quota: 16,
  }),
  "men-formal-shirts": m({
    slug: "men-formal-shirts",
    segment: "men",
    gender: "men",
    productType: "tops",
    subType: "formal-shirt",
    tryOnSupported: true,
    compatibleRelated: ["men-casual-shirts", "men-linen-shirts"],
    sizeProfile: "adult",
    priceBand: "shirt",
    nameTokens: ["shirt", "formal"],
    skuType: "MFS",
    brandSlug: "t360-luxe",
    quota: 14,
  }),
  "men-linen-shirts": m({
    slug: "men-linen-shirts",
    segment: "men",
    gender: "men",
    productType: "tops",
    subType: "linen-shirt",
    tryOnSupported: true,
    compatibleRelated: ["men-casual-shirts", "men-formal-shirts"],
    sizeProfile: "adult",
    priceBand: "shirt",
    nameTokens: ["shirt", "linen"],
    skuType: "MLS",
    brandSlug: "t360-luxe",
    quota: 10,
  }),
  "men-hoodies": m({
    slug: "men-hoodies",
    segment: "men",
    gender: "men",
    productType: "outerwear",
    subType: "hoodie",
    tryOnSupported: true,
    compatibleRelated: ["men-sweatshirts", "men-t-shirts"],
    sizeProfile: "adult",
    priceBand: "outer",
    nameTokens: ["hoodie"],
    skuType: "MHD",
    brandSlug: "t360-active",
    quota: 12,
  }),
  "men-sweatshirts": m({
    slug: "men-sweatshirts",
    segment: "men",
    gender: "men",
    productType: "outerwear",
    subType: "sweatshirt",
    tryOnSupported: true,
    compatibleRelated: ["men-hoodies"],
    sizeProfile: "adult",
    priceBand: "outer",
    nameTokens: ["sweat"],
    skuType: "MSW",
    brandSlug: "t360-active",
    quota: 8,
  }),
  "men-jackets": m({
    slug: "men-jackets",
    segment: "men",
    gender: "men",
    productType: "outerwear",
    subType: "jacket",
    tryOnSupported: true,
    compatibleRelated: ["men-bombers", "men-denim-jackets"],
    sizeProfile: "adult",
    priceBand: "outer",
    nameTokens: ["jacket"],
    skuType: "MJK",
    brandSlug: "t360-luxe",
    quota: 8,
  }),
  "men-bombers": m({
    slug: "men-bombers",
    segment: "men",
    gender: "men",
    productType: "outerwear",
    subType: "bomber",
    tryOnSupported: true,
    compatibleRelated: ["men-jackets", "men-denim-jackets"],
    sizeProfile: "adult",
    priceBand: "outer",
    nameTokens: ["bomber", "jacket"],
    skuType: "MBM",
    brandSlug: "t360-studio",
    quota: 6,
  }),
  "men-denim-jackets": m({
    slug: "men-denim-jackets",
    segment: "men",
    gender: "men",
    productType: "outerwear",
    subType: "denim-jacket",
    tryOnSupported: true,
    compatibleRelated: ["men-jackets", "men-jeans"],
    sizeProfile: "adult",
    priceBand: "outer",
    nameTokens: ["jacket", "denim"],
    skuType: "MDJ",
    brandSlug: "t360-studio",
    quota: 6,
  }),
  "men-jeans": m({
    slug: "men-jeans",
    segment: "men",
    gender: "men",
    productType: "bottoms",
    subType: "jeans",
    tryOnSupported: true,
    compatibleRelated: ["men-chinos", "men-cargos", "men-joggers"],
    sizeProfile: "waist",
    priceBand: "bottom",
    nameTokens: ["jean"],
    skuType: "MJN",
    brandSlug: "t360-essentials",
    quota: 16,
  }),
  "men-chinos": m({
    slug: "men-chinos",
    segment: "men",
    gender: "men",
    productType: "bottoms",
    subType: "chinos",
    tryOnSupported: true,
    compatibleRelated: ["men-jeans", "men-cargos"],
    sizeProfile: "waist",
    priceBand: "bottom",
    nameTokens: ["chino"],
    skuType: "MCH",
    brandSlug: "t360-essentials",
    quota: 10,
  }),
  "men-cargos": m({
    slug: "men-cargos",
    segment: "men",
    gender: "men",
    productType: "bottoms",
    subType: "cargo",
    tryOnSupported: true,
    compatibleRelated: ["men-jeans", "men-joggers"],
    sizeProfile: "waist",
    priceBand: "bottom",
    nameTokens: ["cargo"],
    skuType: "MCG",
    brandSlug: "t360-active",
    quota: 8,
  }),
  "men-joggers": m({
    slug: "men-joggers",
    segment: "men",
    gender: "men",
    productType: "bottoms",
    subType: "joggers",
    tryOnSupported: true,
    compatibleRelated: ["men-shorts", "men-activewear"],
    sizeProfile: "adult",
    priceBand: "bottom",
    nameTokens: ["jogger"],
    skuType: "MJG",
    brandSlug: "t360-active",
    quota: 8,
  }),
  "men-shorts": m({
    slug: "men-shorts",
    segment: "men",
    gender: "men",
    productType: "bottoms",
    subType: "shorts",
    tryOnSupported: true,
    compatibleRelated: ["men-joggers", "men-activewear"],
    sizeProfile: "adult",
    priceBand: "bottom",
    nameTokens: ["short"],
    skuType: "MSH",
    brandSlug: "t360-essentials",
    quota: 8,
  }),
  "men-activewear": m({
    slug: "men-activewear",
    segment: "men",
    gender: "men",
    productType: "active",
    subType: "activewear",
    tryOnSupported: true,
    compatibleRelated: ["men-joggers", "men-shorts", "men-hoodies"],
    sizeProfile: "adult",
    priceBand: "tee",
    nameTokens: ["active", "sport"],
    skuType: "MAC",
    brandSlug: "t360-active",
    quota: 8,
  }),
  "men-kurtas": m({
    slug: "men-kurtas",
    segment: "men",
    gender: "men",
    productType: "ethnic",
    subType: "kurta",
    tryOnSupported: true,
    compatibleRelated: ["men-kurta-sets", "men-nehru-jackets"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["kurta"],
    skuType: "MKT",
    brandSlug: "t360-ethnic",
    quota: 0,
  }),
  "men-kurta-sets": m({
    slug: "men-kurta-sets",
    segment: "men",
    gender: "men",
    productType: "ethnic",
    subType: "kurta-set",
    tryOnSupported: true,
    compatibleRelated: ["men-nehru-jackets"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["kurta"],
    skuType: "MKS",
    brandSlug: "t360-ethnic",
    quota: 8,
  }),
  "men-nehru-jackets": m({
    slug: "men-nehru-jackets",
    segment: "men",
    gender: "men",
    productType: "ethnic",
    subType: "nehru-jacket",
    tryOnSupported: true,
    compatibleRelated: ["men-kurta-sets"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["nehru", "jacket"],
    skuType: "MNJ",
    brandSlug: "t360-festive",
    quota: 6,
  }),

  // â€”â€” Women (~250) â€”â€”
  "women-t-shirts": m({
    slug: "women-t-shirts",
    segment: "women",
    gender: "women",
    productType: "tops",
    subType: "t-shirt",
    tryOnSupported: true,
    compatibleRelated: ["women-tops", "women-blouses"],
    sizeProfile: "adult",
    priceBand: "tee",
    nameTokens: ["t-shirt", "tee"],
    skuType: "WTS",
    brandSlug: "t360-essentials",
    quota: 14,
  }),
  "women-tops": m({
    slug: "women-tops",
    segment: "women",
    gender: "women",
    productType: "tops",
    subType: "top",
    tryOnSupported: true,
    compatibleRelated: ["women-blouses", "women-t-shirts"],
    sizeProfile: "adult",
    priceBand: "tee",
    nameTokens: ["top"],
    skuType: "WTP",
    brandSlug: "t360-studio",
    quota: 18,
  }),
  "women-blouses": m({
    slug: "women-blouses",
    segment: "women",
    gender: "women",
    productType: "tops",
    subType: "blouse",
    tryOnSupported: true,
    compatibleRelated: ["women-tops", "women-kurtis"],
    sizeProfile: "adult",
    priceBand: "shirt",
    nameTokens: ["blouse"],
    skuType: "WBL",
    brandSlug: "t360-luxe",
    quota: 10,
  }),
  "women-casual-dresses": m({
    slug: "women-casual-dresses",
    segment: "women",
    gender: "women",
    productType: "dresses",
    subType: "casual-dress",
    tryOnSupported: true,
    compatibleRelated: ["women-maxi-dresses", "women-mini-dresses", "women-party-dresses"],
    sizeProfile: "adult",
    priceBand: "dress",
    nameTokens: ["dress"],
    skuType: "WCD",
    brandSlug: "t360-studio",
    quota: 16,
  }),
  "women-maxi-dresses": m({
    slug: "women-maxi-dresses",
    segment: "women",
    gender: "women",
    productType: "dresses",
    subType: "maxi-dress",
    tryOnSupported: true,
    compatibleRelated: ["women-casual-dresses", "women-party-dresses"],
    sizeProfile: "adult",
    priceBand: "dress",
    nameTokens: ["dress", "maxi"],
    skuType: "WMD",
    brandSlug: "t360-luxe",
    quota: 12,
  }),
  "women-mini-dresses": m({
    slug: "women-mini-dresses",
    segment: "women",
    gender: "women",
    productType: "dresses",
    subType: "mini-dress",
    tryOnSupported: true,
    compatibleRelated: ["women-casual-dresses", "women-party-dresses"],
    sizeProfile: "adult",
    priceBand: "dress",
    nameTokens: ["dress", "mini"],
    skuType: "WMI",
    brandSlug: "t360-studio",
    quota: 10,
  }),
  "women-party-dresses": m({
    slug: "women-party-dresses",
    segment: "women",
    gender: "women",
    productType: "dresses",
    subType: "party-dress",
    tryOnSupported: true,
    compatibleRelated: ["women-maxi-dresses", "women-casual-dresses"],
    sizeProfile: "adult",
    priceBand: "dress",
    nameTokens: ["dress", "party"],
    skuType: "WPD",
    brandSlug: "t360-luxe",
    quota: 12,
  }),
  "women-kurtis": m({
    slug: "women-kurtis",
    segment: "women",
    gender: "women",
    productType: "ethnic",
    subType: "kurti",
    tryOnSupported: true,
    compatibleRelated: ["women-chudidars", "women-salwar-sets", "women-anarkali"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["kurti"],
    skuType: "WKT",
    brandSlug: "t360-ethnic",
    quota: 16,
  }),
  "women-chudidars": m({
    slug: "women-chudidars",
    segment: "women",
    gender: "women",
    productType: "ethnic",
    subType: "chudidar",
    tryOnSupported: true,
    compatibleRelated: ["women-kurtis", "women-salwar-sets", "women-ethnic-sets"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["chudidar", "churidar"],
    skuType: "WCH",
    brandSlug: "t360-ethnic",
    quota: 21,
  }),
  "women-salwar-sets": m({
    slug: "women-salwar-sets",
    segment: "women",
    gender: "women",
    productType: "ethnic",
    subType: "salwar-set",
    tryOnSupported: true,
    compatibleRelated: ["women-chudidars", "women-kurtis", "women-anarkali"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["salwar"],
    skuType: "WSL",
    brandSlug: "t360-ethnic",
    quota: 10,
  }),
  "women-anarkali": m({
    slug: "women-anarkali",
    segment: "women",
    gender: "women",
    productType: "ethnic",
    subType: "anarkali",
    tryOnSupported: true,
    compatibleRelated: ["women-kurtis", "women-ethnic-sets", "women-chudidars"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["anarkali"],
    skuType: "WAN",
    brandSlug: "t360-festive",
    quota: 10,
  }),
  "women-palazzo-sets": m({
    slug: "women-palazzo-sets",
    segment: "women",
    gender: "women",
    productType: "ethnic",
    subType: "palazzo-set",
    tryOnSupported: true,
    compatibleRelated: ["women-kurtis", "women-ethnic-sets"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["palazzo"],
    skuType: "WPL",
    brandSlug: "t360-ethnic",
    quota: 8,
  }),
  "women-ethnic-sets": m({
    slug: "women-ethnic-sets",
    segment: "women",
    gender: "women",
    productType: "ethnic",
    subType: "ethnic-set",
    tryOnSupported: true,
    compatibleRelated: ["women-chudidars", "women-anarkali", "festival-sets"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["ethnic", "set"],
    skuType: "WES",
    brandSlug: "t360-festive",
    quota: 12,
  }),
  "women-hoodies": m({
    slug: "women-hoodies",
    segment: "women",
    gender: "women",
    productType: "outerwear",
    subType: "hoodie",
    tryOnSupported: true,
    compatibleRelated: ["women-sweatshirts", "women-t-shirts"],
    sizeProfile: "adult",
    priceBand: "outer",
    nameTokens: ["hoodie"],
    skuType: "WHD",
    brandSlug: "t360-active",
    quota: 6,
  }),
  "women-sweatshirts": m({
    slug: "women-sweatshirts",
    segment: "women",
    gender: "women",
    productType: "outerwear",
    subType: "sweatshirt",
    tryOnSupported: true,
    compatibleRelated: ["women-hoodies"],
    sizeProfile: "adult",
    priceBand: "outer",
    nameTokens: ["sweat"],
    skuType: "WSW",
    brandSlug: "t360-active",
    quota: 4,
  }),
  "women-jackets": m({
    slug: "women-jackets",
    segment: "women",
    gender: "women",
    productType: "outerwear",
    subType: "jacket",
    tryOnSupported: true,
    compatibleRelated: ["women-denim-jackets"],
    sizeProfile: "adult",
    priceBand: "outer",
    nameTokens: ["jacket"],
    skuType: "WJK",
    brandSlug: "t360-luxe",
    quota: 6,
  }),
  "women-denim-jackets": m({
    slug: "women-denim-jackets",
    segment: "women",
    gender: "women",
    productType: "outerwear",
    subType: "denim-jacket",
    tryOnSupported: true,
    compatibleRelated: ["women-jackets", "women-jeans"],
    sizeProfile: "adult",
    priceBand: "outer",
    nameTokens: ["jacket", "denim"],
    skuType: "WDJ",
    brandSlug: "t360-studio",
    quota: 4,
  }),
  "women-jeans": m({
    slug: "women-jeans",
    segment: "women",
    gender: "women",
    productType: "bottoms",
    subType: "jeans",
    tryOnSupported: true,
    compatibleRelated: ["women-wide-leg", "women-cargos"],
    sizeProfile: "waist",
    priceBand: "bottom",
    nameTokens: ["jean"],
    skuType: "WJN",
    brandSlug: "t360-essentials",
    quota: 12,
  }),
  "women-wide-leg": m({
    slug: "women-wide-leg",
    segment: "women",
    gender: "women",
    productType: "bottoms",
    subType: "wide-leg",
    tryOnSupported: true,
    compatibleRelated: ["women-jeans", "women-palazzo-sets"],
    sizeProfile: "adult",
    priceBand: "bottom",
    nameTokens: ["wide", "pant"],
    skuType: "WWL",
    brandSlug: "t360-studio",
    quota: 6,
  }),
  "women-cargos": m({
    slug: "women-cargos",
    segment: "women",
    gender: "women",
    productType: "bottoms",
    subType: "cargo",
    tryOnSupported: true,
    compatibleRelated: ["women-jeans", "women-joggers"],
    sizeProfile: "waist",
    priceBand: "bottom",
    nameTokens: ["cargo"],
    skuType: "WCG",
    brandSlug: "t360-active",
    quota: 4,
  }),
  "women-leggings": m({
    slug: "women-leggings",
    segment: "women",
    gender: "women",
    productType: "bottoms",
    subType: "leggings",
    tryOnSupported: true,
    compatibleRelated: ["women-joggers", "women-activewear"],
    sizeProfile: "adult",
    priceBand: "bottom",
    nameTokens: ["legging"],
    skuType: "WLG",
    brandSlug: "t360-active",
    quota: 6,
  }),
  "women-joggers": m({
    slug: "women-joggers",
    segment: "women",
    gender: "women",
    productType: "bottoms",
    subType: "joggers",
    tryOnSupported: true,
    compatibleRelated: ["women-leggings", "women-activewear"],
    sizeProfile: "adult",
    priceBand: "bottom",
    nameTokens: ["jogger"],
    skuType: "WJG",
    brandSlug: "t360-active",
    quota: 4,
  }),
  "women-shorts": m({
    slug: "women-shorts",
    segment: "women",
    gender: "women",
    productType: "bottoms",
    subType: "shorts",
    tryOnSupported: true,
    compatibleRelated: ["women-skirts", "women-activewear"],
    sizeProfile: "adult",
    priceBand: "bottom",
    nameTokens: ["short"],
    skuType: "WSH",
    brandSlug: "t360-essentials",
    quota: 4,
  }),
  "women-skirts": m({
    slug: "women-skirts",
    segment: "women",
    gender: "women",
    productType: "bottoms",
    subType: "skirt",
    tryOnSupported: true,
    compatibleRelated: ["women-shorts", "women-casual-dresses"],
    sizeProfile: "adult",
    priceBand: "bottom",
    nameTokens: ["skirt"],
    skuType: "WSK",
    brandSlug: "t360-studio",
    quota: 8,
  }),
  "women-activewear": m({
    slug: "women-activewear",
    segment: "women",
    gender: "women",
    productType: "active",
    subType: "activewear",
    tryOnSupported: true,
    compatibleRelated: ["women-leggings", "women-joggers"],
    sizeProfile: "adult",
    priceBand: "tee",
    nameTokens: ["active", "sport"],
    skuType: "WAC",
    brandSlug: "t360-active",
    quota: 6,
  }),

  // â€”â€” Kids (~90) â€”â€”
  "kids-boys": m({
    slug: "kids-boys",
    segment: "kids",
    gender: "kids",
    productType: "tops",
    subType: "boys",
    tryOnSupported: true,
    compatibleRelated: ["kids-t-shirts", "kids-shirts"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["kids", "boy"],
    skuType: "KBY",
    brandSlug: "t360-kids",
    quota: 5,
  }),
  "kids-girls": m({
    slug: "kids-girls",
    segment: "kids",
    gender: "kids",
    productType: "dresses",
    subType: "girls",
    tryOnSupported: true,
    compatibleRelated: ["kids-dresses", "kids-frocks"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["kids", "girl"],
    skuType: "KGL",
    brandSlug: "t360-kids",
    quota: 5,
  }),
  "kids-t-shirts": m({
    slug: "kids-t-shirts",
    segment: "kids",
    gender: "kids",
    productType: "tops",
    subType: "t-shirt",
    tryOnSupported: true,
    compatibleRelated: ["kids-graphic-tees", "kids-polos"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["t-shirt", "tee"],
    skuType: "KTS",
    brandSlug: "t360-kids",
    quota: 10,
  }),
  "kids-graphic-tees": m({
    slug: "kids-graphic-tees",
    segment: "kids",
    gender: "kids",
    productType: "tops",
    subType: "graphic-tee",
    tryOnSupported: true,
    compatibleRelated: ["kids-t-shirts"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["t-shirt", "tee", "graphic"],
    skuType: "KGT",
    brandSlug: "t360-kids",
    quota: 6,
  }),
  "kids-polos": m({
    slug: "kids-polos",
    segment: "kids",
    gender: "kids",
    productType: "tops",
    subType: "polo",
    tryOnSupported: true,
    compatibleRelated: ["kids-t-shirts", "kids-shirts"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["polo"],
    skuType: "KPO",
    brandSlug: "t360-kids",
    quota: 5,
  }),
  "kids-shirts": m({
    slug: "kids-shirts",
    segment: "kids",
    gender: "kids",
    productType: "tops",
    subType: "shirt",
    tryOnSupported: true,
    compatibleRelated: ["kids-polos", "kids-t-shirts"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["shirt"],
    skuType: "KSH",
    brandSlug: "t360-kids",
    quota: 5,
  }),
  "kids-hoodies": m({
    slug: "kids-hoodies",
    segment: "kids",
    gender: "kids",
    productType: "outerwear",
    subType: "hoodie",
    tryOnSupported: true,
    compatibleRelated: ["kids-sweatshirts", "kids-jackets"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["hoodie"],
    skuType: "KHD",
    brandSlug: "t360-kids",
    quota: 5,
  }),
  "kids-sweatshirts": m({
    slug: "kids-sweatshirts",
    segment: "kids",
    gender: "kids",
    productType: "outerwear",
    subType: "sweatshirt",
    tryOnSupported: true,
    compatibleRelated: ["kids-hoodies"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["sweat"],
    skuType: "KSW",
    brandSlug: "t360-kids",
    quota: 4,
  }),
  "kids-jackets": m({
    slug: "kids-jackets",
    segment: "kids",
    gender: "kids",
    productType: "outerwear",
    subType: "jacket",
    tryOnSupported: true,
    compatibleRelated: ["kids-hoodies"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["jacket"],
    skuType: "KJK",
    brandSlug: "t360-kids",
    quota: 4,
  }),
  "kids-jeans": m({
    slug: "kids-jeans",
    segment: "kids",
    gender: "kids",
    productType: "bottoms",
    subType: "jeans",
    tryOnSupported: true,
    compatibleRelated: ["kids-joggers", "kids-shorts"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["jean"],
    skuType: "KJN",
    brandSlug: "t360-kids",
    quota: 5,
  }),
  "kids-joggers": m({
    slug: "kids-joggers",
    segment: "kids",
    gender: "kids",
    productType: "bottoms",
    subType: "joggers",
    tryOnSupported: true,
    compatibleRelated: ["kids-shorts", "kids-activewear"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["jogger"],
    skuType: "KJG",
    brandSlug: "t360-kids",
    quota: 4,
  }),
  "kids-shorts": m({
    slug: "kids-shorts",
    segment: "kids",
    gender: "kids",
    productType: "bottoms",
    subType: "shorts",
    tryOnSupported: true,
    compatibleRelated: ["kids-joggers"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["short"],
    skuType: "KSR",
    brandSlug: "t360-kids",
    quota: 4,
  }),
  "kids-dresses": m({
    slug: "kids-dresses",
    segment: "kids",
    gender: "kids",
    productType: "dresses",
    subType: "dress",
    tryOnSupported: true,
    compatibleRelated: ["kids-frocks", "kids-girls"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["dress"],
    skuType: "KDR",
    brandSlug: "t360-kids",
    quota: 12,
  }),
  "kids-frocks": m({
    slug: "kids-frocks",
    segment: "kids",
    gender: "kids",
    productType: "dresses",
    subType: "frock",
    tryOnSupported: true,
    compatibleRelated: ["kids-dresses", "kids-girls"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["frock", "dress"],
    skuType: "KFR",
    brandSlug: "t360-kids",
    quota: 5,
  }),
  "kids-ethnic": m({
    slug: "kids-ethnic",
    segment: "kids",
    gender: "kids",
    productType: "ethnic",
    subType: "ethnic",
    tryOnSupported: true,
    compatibleRelated: ["kids-dresses", "kids-frocks"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["ethnic", "kids"],
    skuType: "KET",
    brandSlug: "t360-kids",
    quota: 5,
  }),
  "kids-activewear": m({
    slug: "kids-activewear",
    segment: "kids",
    gender: "kids",
    productType: "active",
    subType: "activewear",
    tryOnSupported: true,
    compatibleRelated: ["kids-joggers", "kids-shorts"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["active", "sport"],
    skuType: "KAC",
    brandSlug: "t360-kids",
    quota: 4,
  }),
  "kids-sleepwear": m({
    slug: "kids-sleepwear",
    segment: "kids",
    gender: "kids",
    productType: "sleep",
    subType: "sleepwear",
    tryOnSupported: true,
    compatibleRelated: ["kids-sleepwear"],
    sizeProfile: "kids",
    priceBand: "kids",
    nameTokens: ["sleep", "pyjama", "pajama"],
    skuType: "KSL",
    brandSlug: "t360-kids",
    quota: 4,
  }),

  // â€”â€” Sarees (~100) â€”â€”
  "sarees-silk": m({
    slug: "sarees-silk",
    segment: "sarees",
    gender: "women",
    productType: "saree",
    subType: "silk-saree",
    tryOnSupported: true,
    compatibleRelated: ["sarees-cotton", "sarees-party", "sarees-festive"],
    sizeProfile: "one",
    priceBand: "saree",
    nameTokens: ["saree", "silk"],
    skuType: "SILK",
    brandSlug: "t360-heritage",
    quota: 33,
  }),
  "sarees-cotton": m({
    slug: "sarees-cotton",
    segment: "sarees",
    gender: "women",
    productType: "saree",
    subType: "cotton-saree",
    tryOnSupported: true,
    compatibleRelated: ["sarees-silk", "sarees-everyday"],
    sizeProfile: "one",
    priceBand: "saree",
    nameTokens: ["saree", "cotton"],
    skuType: "COT",
    brandSlug: "t360-heritage",
    quota: 20,
  }),
  "sarees-party": m({
    slug: "sarees-party",
    segment: "sarees",
    gender: "women",
    productType: "saree",
    subType: "party-saree",
    tryOnSupported: true,
    compatibleRelated: ["sarees-silk", "sarees-festive"],
    sizeProfile: "one",
    priceBand: "saree",
    nameTokens: ["saree", "party"],
    skuType: "PRTY",
    brandSlug: "t360-festive",
    quota: 20,
  }),
  "sarees-everyday": m({
    slug: "sarees-everyday",
    segment: "sarees",
    gender: "women",
    productType: "saree",
    subType: "everyday-saree",
    tryOnSupported: true,
    compatibleRelated: ["sarees-cotton", "sarees-silk"],
    sizeProfile: "one",
    priceBand: "saree",
    nameTokens: ["saree"],
    skuType: "EVRY",
    brandSlug: "t360-heritage",
    quota: 15,
  }),
  "sarees-festive": m({
    slug: "sarees-festive",
    segment: "sarees",
    gender: "women",
    productType: "saree",
    subType: "festive-saree",
    tryOnSupported: true,
    compatibleRelated: ["sarees-party", "sarees-silk"],
    sizeProfile: "one",
    priceBand: "saree",
    nameTokens: ["saree", "festive"],
    skuType: "FSTV",
    brandSlug: "t360-festive",
    quota: 20,
  }),

  // â€”â€” Wedding (~36) â€”â€”
  "wedding-lehengas": m({
    slug: "wedding-lehengas",
    segment: "wedding",
    gender: "women",
    productType: "bridal",
    subType: "lehenga",
    tryOnSupported: true,
    compatibleRelated: ["wedding-reception", "sarees-silk"],
    sizeProfile: "adult",
    priceBand: "bridal",
    nameTokens: ["lehenga"],
    skuType: "WLH",
    brandSlug: "t360-festive",
    quota: 18,
  }),
  "wedding-sherwanis": m({
    slug: "wedding-sherwanis",
    segment: "wedding",
    gender: "men",
    productType: "bridal",
    subType: "sherwani",
    tryOnSupported: true,
    compatibleRelated: ["men-kurta-sets", "men-nehru-jackets"],
    sizeProfile: "adult",
    priceBand: "bridal",
    nameTokens: ["sherwani"],
    skuType: "WSR",
    brandSlug: "t360-festive",
    quota: 10,
  }),
  "wedding-kurta-sets": m({
    slug: "wedding-kurta-sets",
    segment: "wedding",
    gender: "men",
    productType: "ethnic",
    subType: "kurta-set",
    tryOnSupported: true,
    compatibleRelated: ["men-kurta-sets", "festival-kurtas"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["kurta"],
    skuType: "WKS",
    brandSlug: "t360-ethnic",
    quota: 0,
  }),
  "wedding-reception": m({
    slug: "wedding-reception",
    segment: "wedding",
    gender: "women",
    productType: "bridal",
    subType: "reception",
    tryOnSupported: true,
    compatibleRelated: ["wedding-lehengas", "women-party-dresses"],
    sizeProfile: "adult",
    priceBand: "bridal",
    nameTokens: ["reception", "wedding", "lehenga", "dress"],
    skuType: "WRC",
    brandSlug: "t360-festive",
    quota: 6,
  }),

  // â€”â€” Festival (~16) â€”â€”
  "festival-kurtas": m({
    slug: "festival-kurtas",
    segment: "festival",
    gender: "unisex",
    productType: "ethnic",
    subType: "kurta",
    tryOnSupported: true,
    compatibleRelated: ["men-kurtas", "women-kurtis"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["kurta"],
    skuType: "FKT",
    brandSlug: "t360-festive",
    quota: 0,
  }),
  "festival-dresses": m({
    slug: "festival-dresses",
    segment: "festival",
    gender: "women",
    productType: "dresses",
    subType: "festive-dress",
    tryOnSupported: true,
    compatibleRelated: ["women-party-dresses", "women-ethnic-sets"],
    sizeProfile: "adult",
    priceBand: "dress",
    nameTokens: ["dress", "festive"],
    skuType: "FDR",
    brandSlug: "t360-festive",
    quota: 4,
  }),
  "festival-sets": m({
    slug: "festival-sets",
    segment: "festival",
    gender: "women",
    productType: "ethnic",
    subType: "ethnic-set",
    tryOnSupported: true,
    compatibleRelated: ["women-ethnic-sets", "women-chudidars"],
    sizeProfile: "adult",
    priceBand: "ethnic",
    nameTokens: ["ethnic", "set", "festive"],
    skuType: "FST",
    brandSlug: "t360-festive",
    quota: 4,
  }),
};

export const DEMO_BRANDS = [
  { name: "T360 Essentials", slug: "t360-essentials" },
  { name: "T360 Studio", slug: "t360-studio" },
  { name: "T360 Luxe", slug: "t360-luxe" },
  { name: "T360 Heritage", slug: "t360-heritage" },
  { name: "T360 Active", slug: "t360-active" },
  { name: "T360 Kids", slug: "t360-kids" },
  { name: "T360 Ethnic", slug: "t360-ethnic" },
  { name: "T360 Festive", slug: "t360-festive" },
  { name: "T360 Originals", slug: "t360-originals" },
] as const;

export function getCategoryMeta(slug: string): CategoryMeta | undefined {
  return CATEGORY_META[slug];
}

export function resolveRelatedCategorySlugs(leafSlug: string): string[] {
  const meta = CATEGORY_META[leafSlug];
  if (!meta) return [leafSlug];
  const out = [leafSlug, ...meta.compatibleRelated];
  for (const [slug, m] of Object.entries(CATEGORY_META)) {
    if (slug === leafSlug) continue;
    if (m.segment === meta.segment && m.productType === meta.productType && !out.includes(slug)) {
      out.push(slug);
    }
  }
  return out;
}

export function totalDemoQuota(): number {
  return Object.values(CATEGORY_META).reduce((n, m) => n + m.quota, 0);
}

export function priceForBand(band: PriceBand, i: number): { price: number; salePrice: number | null } {
  const table: Record<PriceBand, number> = {
    tee: 399 + (i % 8) * 200,
    shirt: 699 + (i % 8) * 288,
    bottom: 999 + (i % 7) * 400,
    outer: 1499 + (i % 6) * 500,
    dress: 799 + (i % 8) * 500,
    ethnic: 899 + (i % 8) * 500,
    saree: 1499 + (i % 10) * 1200,
    bridal: 3999 + (i % 8) * 2500,
    kids: 399 + (i % 7) * 250,
  };
  const price = table[band] ?? 999;
  const onSale = i % 4 === 0;
  return { price, salePrice: onSale ? Math.round(price * 0.85) : null };
}

export const __test = { CATEGORY_META, totalDemoQuota };

